# Generated by Django 5.0.6 on 2024-07-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_image_product_slug_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram',
            field=models.TextField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer'),
        ),
    ]
